### ISSUE TITLE
Bigpony loads before MineLittlePony

### ISSUE THREAD

**Issue by fin600** [MineLittlePony/BigPony#10]
MineLittlePony version 1.12.2.3.2
Renaming mod-MineLittlePony to Amod-MineLittlePony fixes the errors.

**Comment by mattmess1221** [comment]
Sadly, liteloader's dependency system has never been very good.

**Comment by Sollace** [comment]
Not a loading order problem but a class version problem. I'll fix it later when I get a chance.
