### ISSUE TITLE
Incompatibility with First Person Models

### ISSUE THREAD

**Issue by meadowsys** [MineLittlePony/BigPony#12]
Hello! When I have this mod and the [First Person Models mod](https://www.curseforge.com/minecraft/mc-mods/first-person-model/) ([their github repository](https://github.com/tr7zw/FirstPersonModel)) installed, the game crashes on launch. I believe it's something to do with this mod modifying the model size and hitbox conflicting with something that First Person Models does.

Here is a crash log with only this mod, First Person Models, and Fabric API: [crash-2021-12-16_12.07.12-client.txt](https://github.com/tr7zw/FirstPersonModel/files/7730129/crash-2021-12-16_12.07.12-client.txt)

Issue on First Person Models repo: tr7zw/FirstPersonModel#244

**Comment by Sollace** [comment]
Yeah, looks like it is a mixin conflict. I'll have to dig into both mods to see how they're conflicting and then see if it can be fixed from my end.

**Comment by Sollace** [comment]
Issue should now be resolved if you install [BigPony 1.6.2](https://github.com/MineLittlePony/BigPony/releases/tag/1.6.2)
