### ISSUE TITLE
Server plugin for BigPony camera changes on Bukkit/Spigot/Paper based servers?

### ISSUE THREAD

**Issue by IDLauncher** [MineLittlePony/BigPony#16]
1. Maybe this is already possible and I don't know it.
2. Maybe this is just technically infeasible.

On a Paper instance I was setting up I saw the "Some features are disabled, contact your server admin" message in the BigPony menu, and doesn't seem like I can just drop the mod and its dependencies into the server plugins to "install it" as the "multiplayer support" section of the readme advises.

Web searched around to see if I could find info on this but came up pretty dry.

Thanks for reading.

**Comment by Sollace** [comment]
You can try running cardboard (or another equivalent server) that should let you run both fabric and paper mods together.

https://www.curseforge.com/minecraft/mc-mods/cardboard

**Comment by MimzyFang** [comment]
as of right now https://modrinth.com/mod/banner is the best mod to run plugins on fabric

**Comment by MimzyFang** [comment]
@Sollace can this be closed as not planned?

**Comment by Sollace** [comment]
Yeah. I have no way to work on a bukkit plugin
