### ISSUE TITLE
autogenerate config with all options on fist launch

### ISSUE THREAD

**Issue by MimzyFang** [MineLittlePony/BigPony#20]
right now it only updates options when the client modifies them but since some options are serverside you have to add them yourself 
I would propose that these options would generate on there default state on fist launch if no config is present

**Comment by Sollace** [comment]
Isn't that already the case? When it generates a config it has all the options set to default.

**Comment by MimzyFang** [comment]
> Isn't that already the case? When it generates a config it has all the options set to default.

not in my experience

**Comment by MimzyFang** [comment]
retested and it works
